Fail if `$HOST` is set but can't be resolved

diff --git a/entrypoint b/entrypoint
--- a/entrypoint
+++ b/entrypoint
@@ -35,20 +35,16 @@ ensure_caps() {
 }
 
 # if `$HOST` is set, look up its IP for use as the destination
-lookup_ip() {
-  if test -n "$HOST"
-  then
-    getent ahostsv4 "$HOST" |
-    awk '!seen[$1]++ { print $1 }' |
-    grep . || die "Couldn't find (IPv4) address for HOST=[$HOST]"
-  fi
+set_ip_by_host() {
+  test -n "$HOST" || return 0
+  IP="$(getent ahostsv4 "$HOST" | awk '!seen[$1]++ { print $1 }')"
+  test -n "$IP" || die "Couldn't find (IPv4) address for HOST=[$HOST]"
 }
 
 # print the IPv4 address of the default gateway
-default_gateway() {
-  ip -4 route show default |
-  awk '{ print $3 }' |
-  grep . || die "Couldn't determine default gateway"
+set_ip_by_default_gateway() {
+  IP="$(ip -4 route show default | awk '{ print $3 }')"
+  test -n "$IP" || die "Couldn't determine default gateway"
 }
 
 # print the current host's IP
@@ -64,10 +60,11 @@ myip() {
 # - IP address of default gateway
 # set default `$PORTS`
 set_destination() {
-  : ${IP:=$(lookup_ip)}
-  : ${IP:=$(default_gateway)}
+  test -n "$IP" ||
+  set_ip_by_host ||
+  set_ip_by_default_gateway ||
+  die "Couldn't determine IP for forwarding"
   : ${PORTS:=0:65535}
-  test -n "$IP" || die "Couldn't determine IP for forwarding"
   export IP PORTS
 }
 
